### PR TITLE
custom OCF theme

### LINKED ISSUE #1: OCF-themed Keycloak login screen
Creating a new Keycloak login theme for OCF

### PR DESCRIPTION
**Pull request by nikhiljha**
closes #1 

I have no idea how this looks, since there isn't really a good way to check, but it should (TM) be safe to test in prod. I swapped out the wallpaper and the logo and some strings.

Based on https://github.com/Alfresco/alfresco-keycloak-theme which is apache licensed.

### CODE REVIEW

**Comment by nikhiljha** [comment]
Also I can't make branches in this repository.

**Comment by dkess** [comment]
What parts of this are modified from Alfresco/alfresco-keycloak-theme?

**Comment by nikhiljha** [comment]
@dkess OCF logo, wallpaper, some strings

**Comment by nikhiljha** [comment]
:(

**Pull request merged**
